vikejs/vike

README.md
boilerplates/index.js

Quick PR to allow the developer to skip the git repo initialization.

feat: allow skip git init

---

README.md

As requested in https://github.com/brillout/vite-plugin-ssr/issues/36#issuecomment-818017489
Let me know if that works for you.
Could provide a basic example soonish, but don't count on that as I'm a little distracted from offline things at the moment 🤪

docs: Add WindiCSS Guide to Readme

---

README.md

As a follow up to https://github.com/brillout/vite-plugin-ssr/pull/37

docs: Add alternative WindiCSS config

---

boilerplates/.testPages.ts
boilerplates/boilerplate-react-ts/pages/_components/Counter.tsx
boilerplates/boilerplate-react-ts/pages/_default/PageLayout.css
boilerplates/boilerplate-react-ts/pages/_default/PageLayout.tsx
boilerplates/boilerplate-react-ts/pages/_default/_default.page.server.tsx
boilerplates/boilerplate-react/pages/_components/Counter.jsx
boilerplates/boilerplate-react/pages/_default/PageLayout.css
boilerplates/boilerplate-react/pages/_default/PageLayout.jsx
boilerplates/boilerplate-react/pages/_default/_default.page.server.jsx
boilerplates/boilerplate-vue-ts/package-lock.json
boilerplates/boilerplate-vue-ts/pages/_components/Counter.vue
boilerplates/boilerplate-vue-ts/pages/_default/PageLayout.vue
boilerplates/boilerplate-vue-ts/pages/_default/_default.page.server.ts
boilerplates/boilerplate-vue/package-lock.json
boilerplates/boilerplate-vue/pages/_components/Counter.vue
boilerplates/boilerplate-vue/pages/_default/PageLayout.vue
boilerplates/boilerplate-vue/pages/_default/_default.page.server.js
boilerplates/package-lock.json

Score Locally is now perfect 100s

Update boilerplates for lighthouse score optimization

---

boilerplates/.testPages.ts
src/getPreloadTags.node.ts

chore: Add mime types to preload tags, add common image preload tags

---

boilerplates/boilerplate-react-ts/server/index.ts
boilerplates/boilerplate-react/server/index.js
boilerplates/boilerplate-vue-ts/server/index.ts
boilerplates/boilerplate-vue/server/index.js

chore: add PORT env option to boilerplates

---

src/ssrEnv.node.ts

Simply adds type to the export to fix #81

fix: export SsrEnv as type

---

vite-plugin-ssr/client/router/useClientRouter.ts

The problems I've fixed in this pull request:
1. When `ensureHydration` is set, the first call of `fetchAndRender` should never abort. Otherwise, follow-up calls will all stuck at `await hydrationPromise`, if user clicks before the first call finishes.
2. Transition should start as soon as user clicks. If transition starts after `await hydrationPromise`, users with slow network will have to wait for initial hydration without any visual indication.
3. I also fixed a typo here.

fix: fix client routing deadlock when ensureHydration is set

---

CONTRIBUTING.md

resolve #283
- Added missing information (guide) on how to resolve dependencies which are required, in order to install `playwright` (which is required to run tests) on debian

Added playwright information for debian

---

vite-plugin-ssr/client/router/prefetch.ts

resolve #285
- Added passive EventListener to touchstart event

Added passive EventListener

---

docs/pages/vue-tour.page.mdx

loose -> lose

---

boilerplates/boilerplate-vue-ts/renderer/types.ts
boilerplates/boilerplate-vue-ts/renderer/usePageContext.ts

Composables can be typed using `InjectionKey`.

Improve types boilerplate vue ts

---

docs/pages/cloudflare-workers.page.mdx

Add an updated example with a shorter worker config, streaming and esbuild.
https://github.com/Immortalin/vite-plugin-ssr-cloudflare-pages-demo

Update cloudflare-workers documentation

---

examples/solid/renderer/_default.page.client.tsx

Make sure all renders are cleaned up before re-rendering

Update solid example client-side rendering

---

vite-plugin-ssr/__internal.d.ts
vite-plugin-ssr/__internal.js
vite-plugin-ssr/__internal/index.ts
vite-plugin-ssr/__internal/setup.d.ts
vite-plugin-ssr/__internal/setup.js
vite-plugin-ssr/node/tsconfig.json
vite-plugin-ssr/package.json

Fixes https://github.com/brillout/vite-plugin-ssr/pull/368#issuecomment-1192610691

fix: add export resolvers for TS

---

docs/pages/build-your-own-framework.page.server.mdx

Fixed a typo in "Build Your Own Framework" page

---

docs/pages/css-in-js.page.server.mdx

Add missing '$' before {dangerouslySkipEscape(collect.getCSS())}

Add missing '$' 

---

examples/react-full/package.json
pnpm-lock.yaml
vite-plugin-ssr/client/router/useClientRouter.ts
vite-plugin-ssr/node/client/router.ts
vite-plugin-ssr/package.json

fixes #501
Read more here https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#packagejson-exports-imports-and-self-referencing

fix: type export

---

docs/pages/deploy-sync.page.server.mdx

docs: update deploy-sync.page.server.mdx

---

docs/pages/stream.page.server.mdx

fix stream type typo

---

docs/pages/prerender.page.server.mdx
vite-plugin-ssr/utils/isReact.ts

docs: fix some typos

---

docs/pages/dynamic-import.page.server.mdx

Originally planned to put the explanation outside of the code, but preferred to leave it as a comment to avoid 'not-seeing the notice' discussions from showing up in the future.

Docs: Type mismatch explanation for dynamic imports with TS

---

examples/solid-ssr-v1/vite.config.ts
examples/solid-ssr/vite.config.ts
vite-plugin-ssr/node/plugin/plugins/buildConfig.ts

chore: remove deprecated polyfillDynamicImport vite option

---

examples/solid-ssr-v1/renderer/+onRenderClient.tsx
examples/solid-ssr/renderer/_default.page.client.tsx

Improve https://github.com/brillout/vite-plugin-ssr/commit/d5c001f11345841a1fd6d21a00ec7daeaf57b5d9
Related #836

chore: improve solid render reconcile

---

vite-plugin-ssr/shared/page-configs/Config.ts

docs: typo

---

vite-plugin-ssr/client/router/prefetch/getPrefetchSettings.ts

getPrefetchSaticAssets -> getPrefetchStaticAssets

refactor: fix typo getPrefetchSaticAssets -> getPrefetchStaticAssets

---

boilerplates/boilerplate-react-ts/server/index.ts
boilerplates/boilerplate-react/server/index.js
boilerplates/boilerplate-vue-ts/server/index.ts
boilerplates/boilerplate-vue/server/index.js
docs/pages/api-routes.page.server.mdx
docs/pages/renderPage.page.server.mdx
vite-plugin-ssr/node/plugin/shared/loggerNotProd.ts
vite-plugin-ssr/node/plugin/shared/loggerNotProd/formatFrameError.spec.ts
vite-plugin-ssr/node/plugin/shared/loggerNotProd/formatFrameError.ts
vite-plugin-ssr/node/plugin/shared/loggerNotProd/log.ts
vite-plugin-ssr/node/runtime/renderPage/handleErrorWithoutErrorPage.ts
vite-plugin-ssr/utils/assert.ts

add warning to make people aware of changes in any files that affecting the server, such as adding api routes, middleware, etc.

docs: Update api-routes.page.server.mdx

---

docs/headings.tsx

docs: fix typo

---

docs/pages/render-modes.page.server.mdx

Tiny fix to update the missing extension in a page filename.

Updates "Render Modes (SPA, SSR, SSG, HTML-only)" to fix a typo

---

vite-plugin-ssr/node/runtime/renderPage/getPageAssets.ts

While digging deeper to make [elysia-vite-plugin-ssr](https://github.com/timnghg/elysia-vite-plugin-ssr) work, I found a working solution, continue of [brillout/vite-plugin-ssr#d410d94](https://github.com/brillout/vite-plugin-ssr/commit/d410d94a021cb2b1a48db5148cc90ceaafffedf5)

fix: oven-sh/bun#3743 - Support Bun

---

.github/workflows/ci.yml
docs/pages/markdown.page.server.mdx
examples/vue-full-v1/package.json
examples/vue-full-v1/pages/_error/+Page.vue
examples/vue-full-v1/pages/markdown/+Page.md
examples/vue-full-v1/readme.md
examples/vue-full-v1/vite.config.ts
examples/vue-full/package.json
examples/vue-full/pages/markdown.page.md
examples/vue-full/vite.config.ts
pnpm-lock.yaml

(See commit messages for more details)

Fixes to Vue examples

---

vite-plugin-ssr/utils/parseUrl.spec.ts
vite-plugin-ssr/utils/parseUrl.ts

@dajinchu What's the after/before benchmark for this PR? 👀
Looking forward to get to the bottom of https://github.com/brillout/vite-plugin-ssr/issues/1115.

perf: stop using `new URL()`

---

docs/pages/aws.page.server.mdx

Thanks for including us! This adds a ref tag to the link so we know users who come from here.

Update Flightcontrol link

---

vike/node/plugin/plugins/buildConfig.ts
vike/node/plugin/plugins/config/index.ts
vike/node/plugin/plugins/devConfig/determineOptimizeDeps.ts
vike/node/plugin/plugins/importUserCode/getVirtualFileImportUserCode.ts
vike/node/plugin/plugins/importUserCode/index.ts
vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.ts
vike/node/plugin/plugins/importUserCode/v1-design/getVirtualFilePageConfigValuesAll.ts
vike/node/plugin/plugins/importUserCode/v1-design/getVirtualFilePageConfigs.ts
vike/node/plugin/shared/findPageFiles.ts
vike/node/prerender/runPrerender.ts
vike/utils/getOutDirs.ts

(attempt to solve #1189)
@brillout @robinelvin with this small patch, an empty `dist/foo/bar.page.js` file doesn't get globbed anymore. Validated with `pnpm run dev|preview|build`, however with `build` there seems to still be a problem, as it fails with
```
vike v0.4.143 pre-rendering HTML...
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
at Xc (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:77:77)
at Z (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
at Yc (/home/.../vike/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/nod …
```

fix: don't glob page files in dist/

---

examples/cloudflare-workers-vue-v1/renderer/+onRenderHtml.ts
examples/custom-preload-v1/renderer/+onRenderHtml.tsx
examples/telefunc-v1/pages/index/+onBeforeRender.ts
examples/telefunc-v1/renderer/+onRenderClient.tsx
examples/telefunc-v1/renderer/types.ts
examples/vue-full-v1/pages/hello/+onBeforePrerenderStart.ts
examples/vue-full-v1/pages/hello/+onBeforeRender.ts
examples/vue-full-v1/pages/hello/+route.ts
examples/vue-full-v1/pages/star-wars/index/+onBeforePrerenderStart.ts
examples/vue-full-v1/pages/star-wars/index/+onBeforeRender.ts
examples/vue-full-v1/pages/star-wars/movie/+onBeforeRender.ts
examples/vue-full-v1/renderer/+onRenderClient.ts
examples/vue-full-v1/renderer/onPageTransitionHooks.ts
pnpm-lock.yaml

@brillout this is the last PR on this topic

examples: add hook types

---

docs/pages/react-query.page.server.mdx

See vikejs/vike-react#30
FYI @phonzammi

docs: add new react-query integration example

---

docs/headings.tsx
docs/pages/css-in-js.page.server.mdx
docs/pages/grommet.page.server.mdx
docs/pages/styled-components.page.server.mdx
docs/pages/styled-jsx.page.server.mdx

docs: add integration example with Grommet

---

docs/pages/react-query.page.server.mdx
docs/pages/tRPC.page.server.mdx

docs: Add new tRPC example repository

---

vike/client/client-routing-runtime/getPageContextFromHooks.ts

If `pageContextInit` has some client data, and onBeforeRender's env is `{ server: true, client: true }`, then the onBeforeRender hook was being called both on server- and client-side upon navigation.

fix double call to onBeforeRender

---

vike/client/client-routing-runtime/getPageContextFromHooks.ts

fix: improve onBeforeRender() env logic

---

examples/auth/package.json
examples/auth/server/index.js
examples/vike-react/package.json
pnpm-lock.yaml

Minor refactor of examples/auth
Since onRenderHtml() of vike-react v0.3.4 has condition : [isSsrDisabled](https://github.com/vikejs/vike-react/blob/24ebe5902e7a86b2145af280574530098647f30c/vike-react/renderer/onRenderHtml.tsx#L36C3-L55C78)
If we don't create our own server/index.ts file (server entry if i am not mistaken), it will just works.
But if we do create custom server/index.ts (like in this example) then we have to return
[stream-pipe](https://vike-v1-staging.lourot.dev/stream#stream-pipes)
```
const { statusCode, headers, earlyHints } = httpResponse
if (res.writeEarlyHints) 
res.writeEarlyHints({ link: earlyHints.map((e) => e.earlyHintLink) })
headers.forEach(([name, value]) => res.setHeader(name, value))
res.status(statusCode)
httpResponse.pipe(res)
```
or …

Minor update examples/auth

---

examples/react-full-v1/renderer/Link.tsx
examples/react-full/renderer/Link.tsx
examples/stem-react/pages/_default/Link.tsx

I stumbled up this while investigating #1281

examples: remove unnecessary type casts

---

docs/headings.tsx
docs/pages/mantine.page.server.mdx

Discussion from Discord: https://discordapp.com/channels/1105779924658303058/1105781552719331371/1181247050646564905
Created example Page for Mantine Template which I made.

Create example page of Mantine

---

vike/node/runtime/html/injectAssets/getHtmlTags.ts

qual: add warning when streaming and pageContext promise

---

docs/pages/injectFilter.page.server.mdx

related to: https://github.com/vikejs/vike/pull/1308
fix: I have forgot to update assetType of injectfilter of the document

Docs: update assetsType of injectfilter

---

docs/headings.tsx
docs/pages/nextui.page.server.mdx

Thanks again @fabioricali. Let us know how things go with Vike. If you feel like helping more, see [contributing](https://github.com/vikejs/vike/issues/1349) and/or consider [sponsoring](https://github.com/sponsors/vikejs) :pray:

docs: add NextUI community example

---

vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/configDefinitionsBuiltIn.ts
vike/node/runtime/renderPage/createHttpResponseObject.ts
vike/node/runtime/renderPage/createHttpResponseObject/getCacheControl.ts
vike/node/runtime/renderPage/getCacheControl.ts
vike/shared/page-configs/Config.ts

Spin-off of #1282. Fixes #1275

feat: cacheControl setting

---

CONTRIBUTING.md
docs/pages/NODE_ENV.page.server.mdx

fix: update some text and link for node docs

fix: update some text and link for node docs

---

vike/node/prerender/runPrerender.ts
vike/shared/hooks/getHook.ts

fix: increase hook timeouts upon pre-rendering

---

docs/pages/meta.page.server.mdx

Close #1300 
I tried my hand at this. I'm not sure if the description for `env.config` is right, I tried figuring out what it does from looking at the code.

add docs for properties in `config.meta`

---

docs/pages/onBeforeRoute.page.server.mdx

respect deprecation of async onBeforeRoute

update docs onBeforeRoute

---

docs/pages/nextjs.page.server.mdx

Add missed character in nextjs.page.server.mdx

---

docs/pages/solid.page.server.mdx

obsoletes
- https://github.com/brillout/vike-with-solid-spa/pull/1
- https://github.com/brillout/vike-with-solid-ssr/pull/1

update community examples of solid

---

vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.ts
vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/filesystemRouting.ts
vike/utils/sorter.ts

This fixes the issues for me, discussed in https://github.com/vikejs/vike/pull/1463
Not sure this is the right place to do it though -  but I tried, can't do it in `sortAfterInheritanceOrder`

fix: sort config value sources

---

vike/shared/page-configs/Config/PageContextConfig.ts

fix: add `Vike.Config` to `PageContextConfig` (fix #1532)

---

docs/pages/route/+Page.mdx

Changed from Route -> RouteSync

Update Route type in +Page.mdx

---

docs/pages/css-frameworks/+Page.mdx
docs/pages/grommet/+Page.mdx
docs/pages/mantine/+Page.mdx
docs/pages/primereact/+Page.mdx
docs/pages/sass/+Page.mdx
docs/pages/styled-components/+Page.mdx
docs/pages/styled-jsx/+Page.mdx
docs/pages/tailwind-css/+Page.mdx
docs/pages/vuetify/+Page.mdx
docs/pages/windi-css/+Page.mdx

- updated style of example list (just into CSS section)
- I'll keep on working to other sections later :)
Related issue: https://github.com/vikejs/vike/issues/1333

Docs: normalize example list of CSS section

---

docs/pages/aws/+Page.mdx
docs/pages/cloudflare-workers/+Page.mdx
docs/pages/netlify-functions/+Page.mdx
docs/pages/vercel/+Page.mdx

related: https://github.com/vikejs/vike/issues/1333
I will continue to work on this Issue in parallel with the creation of the Japanese documentation so that conflicts occur as little as possible:)

docs: normalize example list for `deploy` section

---

docs/pages/pinia/+Page.mdx
docs/pages/vue/+Page.mdx
docs/pages/vuetify/+Page.mdx

This PR lists the [IT4Change frontend boilerplate](https://github.com/IT4Change/boilerplate-frontend/) as example in
- vue
- vuetify
- pinia
Furthermore it changes the structure of the pinia page a bit to be aligned with how examples are listed on the vue & vuetify pages.
The Boilerplate is used in two of our projects
- https://github.com/dreammall-earth/dreammall.earth/tree/master/presenter
- https://github.com/Ocelot-Social-Community/Ocelot-Social/tree/master/frontend
It undergoes regular updates and provides an update mechanism. Hence we believe it could be a valuable contribution to list this project as resource for other developers - may it to copy parts of the code or use it in its entirety.
For more info about the boilerplate consider to read the …

example: IT4Change boilerplate

---

docs/pages/react-query/+Page.mdx
docs/pages/relay/+Page.mdx
docs/pages/socket-io/+Page.mdx
docs/pages/tRPC/+Page.mdx
docs/pages/telefunc/+Page.mdx
docs/pages/urql/+Page.mdx
docs/pages/vue-query/+Page.mdx

related: https://github.com/vikejs/vike/issues/1333
- normalized examples of `Data-fetching` section!

docs: normalize example list  of `Data-fetching`

---

boilerplates/boilerplate-vue-ts/renderer/app.ts
boilerplates/boilerplate-vue/renderer/app.js
examples/layouts-vue/renderer/app.js
examples/layouts-vue/vite.config.js
examples/vue-full/renderer/app.ts
test-deprecated-design/layouts-vue/renderer/app.js
test-deprecated-design/vue-full/renderer/app.ts
test/stream-vue-onServerPrefetch/renderer/app.js

close #1581 
Also see https://github.com/vikejs/vike-vue/pull/81

don't use options api in examples

---

docs/pages/nextjs/+Page.mdx

Add SSG section, clarify SPA-only mode and add links, reorder some content, and expand some subtitles.

Update nextjs comparison

---

docs/pages/nextjs/+Page.mdx

Clarify some headlines, add a link in the table, and move UI framework section down and improve it a bit.

Update nextjs comparison some more

---

docs/pages/pre-rendering/+Page.mdx

Improve the wording and grammatical correctness of the pre-rendering documentation.

docs: pre-rendering wording improvement

---

docs/headingsDetached.tsx
docs/pages/vike-vue/+Page.mdx

FYI @4350pChris, if it's ok for you I will eventually move the entire `README.md` over there.

docs: add /vike-vue

---

docs/headingsDetached.tsx
docs/pages/vike-solid/+Page.mdx

docs: add /vike-solid

---

docs/pages/why/+Page.mdx

To make the benefit clearer from the headline, for those that simply skim.

Update why page: architectural freedom headline

---

vike/utils/parseUrl.spec.ts
vike/utils/parseUrl.ts

Follow up of https://github.com/vikejs/vike/commit/886a99ff21e86a8ca699a25cee7edc184aa058e4#r143308934.

fix: improve url protocol parsing (886a99f#r143308934)

---

docs/headingsDetached.tsx
docs/pages/injectFilter/+Page.mdx
docs/pages/injectScriptsAt/+Page.mdx
docs/pages/settings/+Page.mdx
vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/configDefinitionsBuiltIn.ts
vike/node/runtime/html/injectAssets.ts
vike/node/runtime/html/injectAssets/getHtmlTags.ts
vike/shared/page-configs/Config.ts

Alternative to #1740 
@brillout, Please take a look and review this PR

feat: new setting `injectScriptsAt`

---

docs/pages/injectScriptsAt/+Page.mdx
vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/configDefinitionsBuiltIn.ts
vike/node/runtime/html/injectAssets.ts
vike/node/runtime/html/injectAssets/getHtmlTags.ts
vike/node/runtime/html/injectAssets/injectHtmlTags.ts
vike/node/runtime/html/renderHtml.ts
vike/node/runtime/html/stream.ts
vike/shared/page-configs/Config.ts

Hi @brillout, What do you think of this PR?

fix: support `injectScriptsAt: 'STREAM'`

---

docs/pages/broken-npm-package/+Page.mdx

Docs: fixed url for cyco130/vite-plugin-cjs-interop

---

docs/headings.tsx
docs/pages/effector/+Page.mdx

Hello.
Adding example to documentation about integrating effector with vike react.
Example added to effector org to simplify support for effector team.

docs: Add effector to documentation 

---

docs/pages/releases/2024-08/+Page.mdx

Corrected from `Mantime` to `Mantine`

Update +Page.mdx  (corrected typo)

---

vike/node/runtime/html/injectAssets/getHtmlTags.ts

fix #1856 
@brillout, 
This fix addresses issue #1856. Please feel free to reject this if you believe there is a better approach to resolve the issue.

fix: improve `injectScriptsAt` condition handling

---

docs/pages/routing-precedence/+Page.mdx

Commit 40f84a009a24920422acbbbe4572d2de597b9274 renamed the example file. This PR adjusts sources to changes.

update example references

---

vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/loadFileAtConfigTime.ts
vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.ts

See https://github.com/vikejs/vike-react/pull/151#issuecomment-2481286414.

fix: allow Vike extensions to omit + in file names (vikejs/vike-react#151)

---

docs/headingsDetached.ts
docs/pages/chakra/+Page.mdx
docs/pages/extensions/+Page.mdx

@brillout, Please take a look and review this PR

docs: new page `vike.dev/chakra`

---

vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/crawlPlusFiles.ts

Follow up of https://github.com/vikejs/vike/pull/1688.

fix: fix crawling of symlinked directories

---

vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/crawlPlusFiles.ts

Removing it, as it doesn't work reliably: https://github.com/vikejs/vike/pull/2086.

fix: remove symlink directory crawling

---

vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.ts
vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/crawlPlusFiles.ts
vike/node/plugin/shared/getEnvVarObject.ts

Follow up of https://github.com/vikejs/vike/discussions/2076.

fix: remove `vike({ crawl: { git: false } })` in favor of `VIKE_CRAWL={git:false}`

---

vike/node/api/build.ts
vike/node/api/context.ts
vike/node/api/prepareViteApiCall.ts
vike/node/cli/context.ts
vike/node/cli/entry.ts
vike/node/cli/parseCli.ts
vike/node/cli/utils.ts
vike/node/plugin/plugins/autoFullBuild.ts
vike/node/plugin/plugins/commonConfig.ts
vike/node/prerender/context.ts
vike/node/prerender/runPrerender.ts

https://github.com/vikejs/vike/issues/2123

fix: always start pre-rendering during Vite build (#2123)

---

vike/node/plugin/plugins/buildConfig.ts
vike/node/plugin/plugins/buildEntry/index.ts

fix: fix buildConfig:pre for Environment API (closes #2202)

---

docs/package.json
pnpm-lock.yaml

I've tested it locally, and there were no issues on the dev, the build, or with the style. 
Please give it a try and let me know if I missed anything.
If it looks good to you, let's release a new version, and I'll force-push to this PR.

chore: bump `@brillout/docpress`

---

docs/headings.ts
docs/pages/config/+Page.mdx
docs/pages/injectFilter/+Page.mdx
docs/pages/server/+Page.mdx

@magne4000 Removed/changed a couple of sentences; the overall structure is the same.

docs: polish /server

---

vike/node/api/dev.ts
vike/node/cli/entry.ts

See https://github.com/vikejs/vike-node/pull/64#discussion_r2006393692

fix: don't make CLI listen in middleware mode

---

docs/pages/server/+Page.mdx

@magne4000 Is that accurate? It's only for Hono right?

docs: document hono serve passed down options (vikejs/vike-server#88)

---

docs/pages/aws/+Page.mdx

Added an example of a real app using Vike with SSR Streaming + SST + Hono
You can access the app at https://rentvsbuy.io/
I am happy to also create a dedicated starter template repository, would be good for someone to give my repo a quick look to make sure I am not doing anything too egregious

docs: add example of real application using Vike + SST and Hono

---

examples/i18n/.testRun.ts
examples/i18n/locales/translations.js
examples/i18n/pages/+onPrerenderStart.js
examples/i18n/pages/_error/+Page.jsx
test-deprecated-design/i18n/.test-dev.test.ts
test-deprecated-design/i18n/.test-preview.test.ts
vike/node/plugin/plugins/commonConfig.ts
vike/node/prerender/runPrerender.ts
vike/node/runtime/renderPage/renderPageAlreadyRouted.ts

See https://vike.dev/i18n#pre-rendering.

fix: add 404 page to prerenderContext.pageContexts

---

docs/pages/index/sections/features/chip/Chip.tsx

Align numbers in chip diagram

---

FEATURES.md
docs/+redirects.ts
docs/headings.ts
docs/pages/csp/+Page.mdx
docs/pages/headers/+Page.mdx
docs/pages/pageContext/+Page.mdx
packages/vike/node/runtime/csp.ts
packages/vike/node/runtime/html/injectAssets/getHtmlTags.ts
packages/vike/node/runtime/html/injectAssets/inferHtmlTags.ts
packages/vike/node/runtime/html/injectAssets/mergeScriptTags.ts
packages/vike/node/runtime/html/serializeContext.ts
packages/vike/node/runtime/renderPage/csp.ts
packages/vike/node/runtime/renderPage/loadPageConfigsLazyServerSide.ts
packages/vike/node/vite/shared/resolveVikeConfigInternal/configDefinitionsBuiltIn.ts
packages/vike/shared/page-configs/resolveVikeConfigPublic.ts
packages/vike/types/Config.ts
packages/vike/types/PageContext.ts
test/playground/+config.ts
test/playground/pages/e2e-test.ts
test/preload/__snapshots__/dev.spec.ts.snap
test/preload/__snapshots__/prod.spec.ts.snap
test/preload/renderer/+config.js
test/preload/testRun.ts

Follow up of https://github.com/vikejs/vike/pull/2639.

feat: CSP support (closes #1554)

---

docs/pages/vike-react/+Page.mdx
docs/pages/vike-solid/+Page.mdx
docs/pages/vike-vue/+Page.mdx

For me this was not immediately clear, so would be good to have this information on this page. I think it is an essential part of getting started with `vike-react`.

docs: Document how to add a page after configuring vike-react

---

docs/components/CommunityNote.tsx
docs/pages/deno/+Page.mdx

Documentation for deno implementation 👍

docs: improve /deno
