src/client/router/index.node.ts
Just a small thing I noticed!
Also note the Readme appears to be incorrect in this area, it states `In Node.js, navigate() is a no-op.`, which is not correct.
=> Fix typo in `navigate` error

CONTRIBUTING.md
The project uses Node workspaces which were added in Node 15. I had my default set to Node 14 and the setup instructions didn't work. Probably best to indicate this requirement to potential contributors.
=> indicate Node 15 requirement in contribution docs

src/client/navigationState.client.ts, src/client/router/getPageByUrl.client.ts, src/client/router/getPageId.client.ts, src/client/router/getPageProps.client.ts, src/client/router/useClientRouter.client.ts
This PR allows for fetching page props for a prospective new URL _before the URL has changed_. This is ideal/required when fetching data in client-side navigation hooks that occur before the navigation has completed.
Additionally, I removed the concept of "navigationChanged" for the following reasons:
- When our URL matches the initial URL, we probably DO want to serve the values cached to the DOM by the SSR process. E.g. even if we navigate off of the initial route, then go back to it, why would we make a network request for that data when it is still sitting in DOM (as it was when the app initialized)?
- It seemed strange to be setting navigation state in a method responsible for fetching data ("getPageProps" does not sound like it would/should have side effects).
=> fix: allow fetching new page props before url change

src/getPreloadTags.node.ts
Per https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content
Using `as` to specify the type of content to be preloaded allows the browser to:
- Prioritize resource loading more accurately.
- Store in the cache for future requests, reusing the resource if appropriate.
- Apply the correct content security policy to the resource.
- Set the correct Accept request headers for it.
It should also resolve this error in Safari (at least for the stylesheet, not so much the `svg` - open to ideas there):
=> Set `as` properly on preload tags.

examples/base-url/package-lock.json, examples/base-url/package.json, examples/react/package-lock.json, examples/react/package.json, examples/vue/package-lock.json, examples/vue/package.json, package-lock.json, package.json
This PR replaces `rm -rf` with rimraf to ensure it works properly on Windows (in the same way it is done on `vite` and other packages).
Fixes #74
=> fix: fixes build process on Windows

README.md
Fix a missing `'` character on docs.
=> docs: minor

src/client/router/useClientRouter.client.ts
Navigating back with the client router works only once or not all. You can try that in the **react-full** example. Run `npm run dev`, go to `http://localhost:3000`, click on a link in the menu, click the browser back button and watch the console. Either this already failed or if not go forward again. This error message appears:
```
Uncaught TypeError: can't access property "scrollPosition", obj is undefined
hasProp hasProp.ts:22
getScrollPositionFromHistory useClientRouter.client.ts:243
onBrowserHistoryNavigation useClientRouter.client.ts:199
```
The problem seems to be that you set the history state to undefined in the changeUrl function:
https://github.com/brillout/vite-plugin-ssr/blob/191b073ea2c4232dfa2d7626a2f1768cd13ef3a9/src/client/router/useClientRouter.client.ts#L208
And try to …
=> Fix getting scroll position from history

vite-plugin-ssr/node/html/inferMediaType.ts
To fix the following console warning when including webp images:
> Preload of http://localhost:3000/assets/image.webp was ignored due to unknown “as” or “type” values, or non-matching “media” attribute.
=> Add webp to inferred types

examples/react-full/.testPages.ts, vite-plugin-ssr/node/html/injectAssets.ts
Currently vite-plugin-ssr injects link tags (stylesheets, preload links, etc.) at the very start of head, before any application defined head tags.
It makes it rather difficult to use `<meta http-equiv="X-UA-Compatible" content="IE=Edge">`, which must be the first.
Also it is a bit more robust, idiomatic and performant to put `<meta charset>`, `<title>` and `<meta name="viewport">` (and other critical meta tags or resources) near the start, so that charset detection, title and layout are not blocked or delayed.
This PR changes link tags to be injected at the end of head by default, or at the verbatim string `` (which is replaced).
=> Inject link tags at the end of head or custom point

vite-plugin-ssr/node/html/inferMediaType.ts
When using scss/sass/less fixes console warning (#196)
and makes SSR css to load with html in dev mode which removes page flickering and layout shifting after client css is loaded
=> Add scss/sass/less to inferred types

examples/vercel/package.json, examples/vercel/vercel/deploy.sh, yarn.lock
I made some assumptions when updating javascript example, based on my typescript project. It turned out that it didn't work. Theoretically, Vercel should bundle javascript serverless functions on their side, but they do not do that. This PR adds another step in deployment process, which uses [@vercel/ncc](https://github.com/vercel/ncc) tool which bundles entire app to a single, lambda-friendly file.
=> [Fix] Bundle app before deploying to Vercel

docs/renderer/_default.page.server.tsx
I think setting `appId` is what tells Algolia DocSearch to use v3, so we need to update the apiKey being used as well.
=> docs: update Algolia apiKey for v3

docs/pages/github-pages.page.mdx
The `vite-plugin-ssr.com`  link to workflow example was pointing to a 404 Page.
https://github.com/brillout/vite-plugin-ssr/blob/master/.github/workflows/docs-website.yml
Instead of:
https://github.com/brillout/vite-plugin-ssr/blob/master/.github/workflows/docs.yml
=> Fixed broken link to workflow example

docs/pages/catch-all.page.mdx
none
- Fixed typo in line 13
```js
export default '/product/*`
```
=> Fixed typo in code example

vite-plugin-ssr/utils/parseUrl.ts
The current code uses `decodeURI` on `url` then asserts that it `isParsable` which does a second `decodeURI`. If the initial decoded URI contains a `%` character, the second `decodeURI` in `isParsable` will fail. Asserting `isParsable` before the `decodeURI` in `parseUrl` allows a `url` containing a decoded `%` character to be parsed successfully.
=> Fix duplicate decodeURI logic

docs/pages/nested-routes.page.mdx
Changed the typo "Cient rendering" to "Client rendering" at line 48.
=> Fixed typo in the documentation for Nested Routes

docs/pages/index/features/Features.tsx
Just a typo on `Craftsmanship` a S was missing.
Thanks a lot for this amazing work 👌🏻
=> fix: typo on craftsmanship

vite-plugin-ssr/node/plugin/plugins/generateImportGlobs/getGlobRoots.ts
> VPS symlinking the framework pageFilesDir to node_modules breaks exports from the framework (since it doesn't copy contents other than pageFilesDir, which  means that files including package.json is not there)
Fixes issue [mentioned here](https://discord.com/channels/815937377888632913/815937377888632916/969417390771290182)
=> fix: isolate framework pageFiles symlink directory

examples/react-router/package.json, examples/react-router/pages/all.page.jsx, examples/react-router/renderer/_default.page.server.jsx, pnpm-lock.yaml
react-router v6 made some breaking changes for the examples.
one important change was `Route component={<Component/>}` to `Route element={<Component/>}` among others.
=> bump react-router to v6 in examples/react-router

examples/graphql-apollo-vue/rendered/_default.page.client.js, examples/graphql-apollo-vue/rendered/_default.page.server.js
Hello. In graphql-view example console.log outputs an error, because the server side passes an empty cache object.
This pull request fix it.
=> fix apollo cache in .page.server (vue apollo example)

examples/graphql-apollo-react/package.json, examples/graphql-apollo-react/server/index.js, examples/graphql-apollo-vue/.testRun.ts, examples/graphql-apollo-vue/package.json, examples/graphql-apollo-vue/server/index.js, pnpm-lock.yaml
Updating dependencies to `latest` to demo `@apollo/client` usage with `vite` v3. After updating, the only deprecation warning was the following:
Making that prescribed change to the options passed to `vite.createServer` eliminated the warning. The demo app runs as expected and behaves as it did when previously built with `vite` v2:
=> chore(deps): update dependencies to latest to demo Apollo Client with Vite 3

vite-plugin-ssr/__internal.ts, vite-plugin-ssr/node/prerender.ts, vite-plugin-ssr/node/tsconfig.json, vite-plugin-ssr/package.json, vite-plugin-ssr/shared/setProduction.ts
- `page-files/setup`: For other helpers to work
- `shared/route`: Need `loadPageRoutes` and `route` functions
- `shared/getPageFiles`: Need `getPageFilesAllServerSide`
Will be mergeable when `vite-plugin-vercel` compiles correctly and without hacks.
=> Export helpers needed by vite-plugin-vercel vps integration

pnpm-lock.yaml, vite-plugin-ssr/package.json, vite-plugin-ssr/tsconfig.base.json
I'm learning the source code for VPS, and I found local debugging inconvenient, so I did these things:
1. add typescript sourcemap, and ignore `.map` from `npm publish`
2. replace `rimraf` for `rm -rf` as windows do not support it.
Sorry for my bad english. If I did something wrong, please tell me!
=> chore: add sourcemap for debug

.github/workflows/ci.yml, vite-plugin-ssr/node/prerender.ts, vite-plugin-ssr/utils/objectAssign.ts
While working on `vite-plugin-vercel` I noticed that prerender was only generating `.pageContext.json` files, twice.
Same `pageContext` is used for a page `.html` and `.pageContext.json`, resulting in `_prerenderResult` being overwritten in parallel runs, before `onPagePrerender` finishes its execution.
`objectAssign` can also now take any number of args, like `Object.assign` would.
=> fix: make onPagePrerender pageContext concurrent safe

boilerplates/boilerplate-react-ts/renderer/_default.page.server.tsx, boilerplates/boilerplate-react-ts/renderer/types.ts, boilerplates/boilerplate-react/renderer/_default.page.server.jsx, boilerplates/boilerplate-vue-ts/renderer/_default.page.server.ts, boilerplates/boilerplate-vue-ts/renderer/types.ts, boilerplates/boilerplate-vue/renderer/_default.page.server.js
[Line 24](https://github.com/brillout/vite-plugin-ssr/blob/158059610a9a76611b5f43576dcee6b1e8ab0f92/boilerplates/boilerplate-react-ts/renderer/_default.page.server.tsx#L24): 
```
const { documentProps } = pageContext;
const title = (documentProps && documentProps.title) || 'Vite SSR app';
```
I believe this should be `const { documentProps } = pageContext.exports;`
Which also needs to be resolved downstream in ./types.ts
=> Fix minor documentProps error

examples/solid-spa/renderer/_default.page.client.tsx
Fixes a bug in #430. 
Each route change resulted in appending DOM nodes without the disposal of previous DOM nodes.
https://user-images.githubusercontent.com/35429197/188263852-8b700add-c211-4bb8-aac9-3e1fe3fb1c3c.mov
=> fix: disposing of previous page

docs/pages/renderPage.page.server.mdx, test/renderPage.spec.ts, vite-plugin-ssr/node/renderPage.ts
This PR fixes streaming SSR on Firefox.
Firefox streams the HTML content only if `Content-Type` has `charset`, therefore the previous version didn't do streaming SSR on Firefox since `contentType` was `text/html` which doesn't include `charset`.
=> fix: make streaming SSR work on Firefox

docs/pages/pre-rendering.page.server.mdx
Links are broken currently and are missing an `/index`.
=> [fix] broken links

docs/pages/vercel.page.server.mdx
Hey there! 👋 
Thanks again for this amazing library. Wanted to update the Vercel docs to clarify a few things. First, we should probably recommend deploying with `vite-plugin-vercel` to enable support for all Vercel features. This is no longer a fast-moving target (sorry for the changes between v1 and v3) and has now stabilized. The Build Output API is what all of the meta-frameworks on Vercel and moving towards targeting, including SvelteKit, Nuxt, Astro, and more.
Learn more: https://vercel.com/blog/build-output-api
=> Update Vercel documentation.

vite-plugin-ssr/node/html/injectAssets/injectHtmlSnippet.ts
Hello @brillout! Thank you for your awesome work on this plugin. I love it's flexibility and ease of use.
I am building quite a large SSR project around it and seeking the best possible performance. I've noticed, there is a non-negligible framework overhead. So I started profiling the costly functions calls. Surprisingly, all the expensive operations are located in `injectHtmlSnippet.ts`. There was very inefficient `getTagClosing` using `String.includes` and lowercasing all html... I refactored this function using `RegExp` as in `tagClosingExists`. The result is the whole `injectAssetsToStream` operation is approx. 3.5x faster.
BEFORE:
AFTER:
I have also noticed a lot of `assert()` to heavy check results during runtime. However, those runtime "double" or sometimes "tripple" checks where …
=> Improve getTagClosing performance

boilerplates/index.js
Previously, running `npm init vite-plugin-ssr@latest` would include a few logs from git that were cluttering the scaffolder's output. This change prevents git from logging to the user's terminal when initializing the new git repository and creating the first commit. 
See #478 for full details.
=> chore: ignore git logs during new app scaffolding

vite-plugin-ssr/node/renderPage.ts, vite-plugin-ssr/shared/addComputedUrlProps.ts, vite-plugin-ssr/shared/types.ts
Replaced "Outdated" with JSDoc `@deprecated`. IDEs now show deprecation hints inline.
This PR is naive. I simply CMD + F the repo for "Outdated" and replaced "Outdated" with @deprecated.
=> use jsdoc deprecated

docs/pages/page-redirection.page.server.mdx
It took me some time to realize that vite-plugin-ssr provides no built-in redirect functionality. Makes sense but should probably be mentioned in the docs.
=> provide info for redirect

docs/pages/routing-precedence.page.server.mdx
To me, the "routing precedence" appears a bit confusing. 
because the order of the examples is not correct.
you mention " Example (4) + (6) + (7):" 
but I think the order of the following examples is incorrect.   
currently the Example with the number "6" is in the first position and "4" in the second. 
I changed the order and added a number to the examples. 
Examples: 
4 =
```js
// product/list.page.route.js
export default '/product'
```
6:
```js
// product/item.page.route.js
export default '/product/@productId'
```
7:
/ product/catch-all.page.route.js
.......
=> changed the order of the e.g.  and added a Number

docs/pages/docker.page.server.mdx
As the title says, correcting a small typo in the Docker section of the documentation.
=> Correct typo in Docker section

vite-plugin-ssr/node/html/stream.ts
This PR fixes a minor bug that the streaming not starting when the writable pipe from `render()` wrote the initial chunk synchronously.
=> fix: pipe original stream asynchronously

docs/pages/index/features/Features.tsx
Upsteam is a typo. The other changes are a little more subjective, can remove them if you think it's unnecessary.
=> Typo + grammar clarification

examples/vue-router/pages/all.page.server.js
We should use `router.push(pageContext.urlOriginal)` but not `urlPathname`, for pass query and hash to the renderer
=> Update `all.page.server.js`, fixed server side route

docs/headings.tsx, docs/pages/styled-jsx.page.server.mdx
Hey @brillout ! 
Following up with my own example, let me know if anything needs tweaking.
=> add docs to use styled-jsx with the plugin

docs/pages/data-fetching.page.server.mdx
There is duplicate `Page` declarations which results with this error:
I believe the intent was to showcase the `pageProps` being available, so I removed the first declaration with `Page` and kept the second one.
=> Fixes "Data Fetching" docs

vite-plugin-ssr/utils/parseUrl.ts
Improves https://github.com/brillout/vite-plugin-ssr/issues/1115 by removing try/catch to avoid error handling overhead when pathname is relative and no `base` is passed to URL constructor.
Benchmark using the `npm create vite-plugin-ssr starter` repo on the index page. Used [bombardier](https://github.com/codesenberg/bombardier) on Macbook with M1 Pro.
before:
```
Statistics        Avg      Stdev        Max
Reqs/sec      1312.95     223.14    3744.83
Latency       94.75ms    17.55ms   244.31ms
```
after:
```
Statistics        Avg      Stdev        Max
Reqs/sec      2269.03     439.82    6707.62
Latency       54.98ms    12.65ms   190.80ms
```
=> Faster URL Parsing

vike/shared/page-configs/utils.ts, vike/types/defineConfig.ts, vike/types/index.ts
Resolves #1156 
This PR adds a `defineVikeConfig` helper.
The name could be changed to `definePageConfig`, but from what I've seen in the repo, `PageConfig` is something different?
=> feat: add defineVikeConfig helper

vike/node/plugin/plugins/suppressRollupWarning.ts
Since [Rollup 3.25.0](https://github.com/rollup/rollup/releases/tag/v3.25.0), it introduced the `RollupLog` type in favour of `RollupWarning` as it supports `this.info`, `this.warn`, etc. `RollupWarning` was made an alias of `RollupLog`.
In Rollup 4 which Vite 5 uses, `RollupWarning` was removed. In this PR, I updated to use `RollupLog` instead.
=> refactor: update rollup warning types

vike/utils/parseUrl.spec.ts, vike/utils/parseUrl.ts
This fixes https://github.com/vikejs/vike/issues/1205
* I made sure search params with the `constructor` key in URLs don't make parseUrl() blow up.
* Also fixed a few typos
In following code
```ts
searchAll[key] = [...(searchAll[key] || []), val]
```
when `searchAll[key]` is accessed the first time it is typically `undefined` and `searchAll[key] || []` evaluates as an empty array resulting in `searchAll[key] = [val]`. However, if `key` is `'constructor'` `searchAll['constructor']` is a function resulting `searchAll['constructor'] || []` to be a function, which is not iterable, hence `...(searchAll[key] || [])` throws an error.
One possible solution to the issue is checking if `searchAll[key]` is an array and spread it only if so, otherwise fall back to the empty array.
=> Allow "constructor" search param in URL

vike/node/runtime/renderPage/createHttpResponseObject/assertNoInfiniteHttpRedirect.ts, vike/shared/route/resolveRedirects.spec.ts, vike/shared/route/resolveRedirects.ts, vike/utils/parseUrl-extras.ts
resolves #1245
This PR introduces the capability to utilize the mailto protocol within the redirect configuration. 
This allows for configured path to be redirected to email addresses, triggering the opening of the user's default email client. 
config example
```javascript
// vite.config.js
import vike from 'vike/plugin'
export default {
plugins: [
vike({
redirects: {
'/email': 'mailto:foo@bar.test'
}
})
]
}
```
=> Enable any protocol support for redirects

docs/pages/preload.page.server.mdx
I collected typo `stc` to `src` at docs!
=> Docs: fixed typo `stc`

docs/pages/preload.page.server.mdx, vike/node/runtime/renderPage/getPageAssets/sortPageAssetsForEarlyHintsHeader.ts, vike/node/runtime/renderPage/inferMediaType.ts, vike/node/runtime/renderPage/loadPageFilesServerSide.ts
Issue: https://github.com/vikejs/vike/issues/1299
I've added preload tags such as `video`, `audio` and more (all from [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-as)
If there are something wrong or missing, i'd be happy if you let me know...!!
=> Add preload tags to `injectFilter`

examples/react-full/pages/hello/+Page.tsx, examples/react-full/pages/star-wars/@id/+Page.tsx, examples/react-full/pages/star-wars/@id/+data.tsx, examples/react-full/pages/star-wars/index/+Page.tsx, examples/react-full/pages/star-wars/index/+data.ts, examples/react-full/pages/star-wars/index/+onBeforePrerenderStart.ts, examples/react-full/renderer/+onRenderClient.tsx, examples/react-full/renderer/+onRenderHtml.tsx, examples/react-full/renderer/PageContext.ts, examples/react-full/renderer/useData.tsx, vike/shared/page-configs/Config.ts
Needed by https://github.com/vikejs/vike-vue/pull/52
@brillout it works :) I have updated the `react-full` example accordingly, which makes the `react-data-fetching` example obsolete, by the way. If you like this DX I will:
1. adapt `vue-full` in the same way
2. delete `react-data-fetching`
3. document this at https://vike.dev/onBeforePrerenderStart
=> feat: generic `<Data>` type for `onBeforePrerenderStart()`

vike/node/shared/extractAssetsQuery.ts
I'm not sure what `extractAssetsRemoveQuery()` functions should do exactly, but this fixes the problem reported in #1419 for me.
Fixes #1419
=> Fix `Could not load virtual:vike:pageConfigValuesAll`

docs/pages/file-env/+Page.mdx
line says `export deault` it seems like that was intended to be `export default`
=> Correct typo in file-env

vike/utils/parseUrl.ts
I've tested it in Electron, and work fine with 'file://' protocol.
=> support Electron by adding 'file://' protocol

docs/pages/i18n/+Page.mdx, vike/shared/addUrlComputedProps.ts
Pass the query parameters to 'urlLogical' in the i18n doc.
So the pages can access the parameters.
=> i18n doc: pass query params to 'urlLogical'

vike/client/client-routing-runtime/history.ts
When Vike monkey patches `history.pushState`, it saves the "original" pushState to call during Vike's routing. However, 3rd party libraries also monkey patch `pushState` in order to be informed when the page changes (in my case, [Amplitude](https://github.com/amplitude/Amplitude-TypeScript)). These libraries will not be informed when Vike navigates.
This PR changes Vike's navigation to go through `history.pushState` so that any monkey patches that happen _after_ Vike's will still run. It detects whether Vike's own navigation is happening to no-op the monkey patch.
=> Fix PushState MonkeyPatch

vike/node/plugin/shared/addSsrMiddleware.ts, vike/node/runtime/renderPage.ts, vike/node/runtime/renderPage/renderPageAlreadyRouted.ts, vike/shared/sortPageContext.ts
In many cases we need to access cookie in SSR codes. You described correctly how we can pass it to `pageContext` in `server/index.ts` file. 
But it is just effective for production mode. I realized in dev mode, passing header items using Vike Vite plugin was applied for 'user-agent' only, but not for cookie.
I passed `cookie` to `pageContext` like `user-agent` in Vike plugin.
=> feat: add cookie to pageContext for dev mode

vike/node/plugin/plugins/devConfig/index.ts
@brillout 
Let me try this with '@hono/vite-dev-server' first.
I'll try to add a test later.
Cmiiw and Let me know if you have anything else to add.
=> fix: improve addSsrMiddleware() condition

docs/headingsDetached.tsx, docs/pages/meta/+Page.mdx, docs/pages/react/+Page.mdx, docs/pages/streaming/+Page.mdx, docs/pages/vike-react/+Page.mdx
FYI @4350pChris @magne4000 I moved the `README.md` content of `vike-react` to `vike.dev`. You can do the same but I think it's also fine if you keep things as they are.
=> docs: add /vike-react

vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/crawlPlusFiles.ts
Also there is example, which works fine with symlinks with this PR changes: https://github.com/iserdmi/vike-link-example/tree/master
Symlinks should be relative and also not be gitignored. Because if them gitignored it is not possible to get their mode with `$ git ls-file`
=> Add symlinks support

docs/pages/onBeforeRender/+Page.mdx
There's no `export` in the TypeScript example code.
=> docs: minor fix

docs/pages/fastify/+Page.mdx
Fix a small typo in `pages/fastify/+Page.mdx`
=> docs: fix typo

vike/node/runtime/renderPage/inferMediaType.ts
Adds `.avif` files to mediatype inference, as it was not previously contemplated by the logic.
=> Mediatype: add avif to mediatype inference

vike/node/runtime/html/injectAssets.ts, vike/node/runtime/html/injectAssets/getHtmlTags.ts, vike/node/runtime/html/injectAssets/injectHtmlTags.ts, vike/shared/page-configs/Config.ts
@phonzammi I made it a hard breaking change, as I guess `vike-solid` is the only user using `injectScriptsAt: 'STREAM'`. Make to sure to update the `+require` value of `vike-solid` to the Vike version I'm about to release.
=> fix: rename STREAM to HTML_STREAM

vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/transpileAndExecuteFile.ts
`pointerImports` is never reassigned
=> minor refactor

docs/pages/abort/+Page.mdx
Tiny, low-priority PR/suggestion fixing a small typo, 'nuthsell' should be 'nutshell'!
=> docs: Correct spelling of nutshell in abort documentation

docs/pages/antd/+Page.mdx, docs/pages/extensions/+Page.mdx, docs/pages/releases/2024-09/+Page.mdx
Docs updated :
> * vike.dev/antd
> * vike.dev/extensions
Please take a look and review it. 
I'm not sure about : 
> * vike.dev/releases/2024-09 (I should rename and publish it at some point 😅)
=> docs: mention new extension `vike-react-antd`

docs/pages/meta/+Page.mdx
The `Effect` type is deprecated according to the code comments, so the examples in the docs should be updated accordingly.
https://github.com/vikejs/vike/blob/4dcddbc6b875a9da196747e939b9c8a6de70f5a0/vike/types/index.ts#L67-L74
=> docs: replace deprecated Effect type with ConfigEffect

.gitignore
Depending on your checkout method and setup (for example, within a VS Code DevContainer), `pnpm` creates a `.pnpm-store` folder at the root of your workspace that should be ignored by `git`.
Not ignoring it can cause quite a headache and >10,000 untracked changes due to files in `.pnpm-store`.
=> fix: add `.pnpm-store` to `.gitignore`

docs/pages/new/+Page.mdx
Example project link for vue-minimal is leading to react-minimal.
=> Fix a docs link to the vue-minimal example

pnpm-lock.yaml, test/middleware-config/express-entry.ts, test/middleware-config/package.json, test/middleware-config/pages/middlewareTelefunc.ts, test/middleware-config/pages/middlewareVike.ts
WIP around how we can move some logic used in `+middleware.ts` process to `universal-middleware`.
@brillout This is mostly to discuss what we should port to `universal-middleware` and create a proper API.
`universal-middleware` in progress PR: https://github.com/magne4000/universal-middleware/pull/95
=> +middleware example with @universal-middleware/router

docs/pages/filesystem-routing/+Page.mdx, docs/pages/nextjs/+Page.mdx, pnpm-lock.yaml, vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/crawlPlusFiles.ts, vike/node/plugin/shared/findPageFiles.ts, vike/package.json, vike/utils/findFile.ts
The docs say:
>## Minimal and self-contained (no deps)
>
>[All dependencies](https://github.com/vikejs/vike/blob/3d042da/vike/package.json#L15-L26) are either shared with Vite (e.g. [`fast-glob`](docs/pages/nextjs/+Page.mdx:))
But actually Vite switched to tinyglobby. There's also a PR out to switch vitest to tinyglobby. I thought it'd be good to stay aligned here
`fast-glob` has 17 dependencies vs just 2 for `tinyglobby`
=> perf: switch from `fast-glob` to `tinyglobby`

vike/node/runtime/html/stream.ts
Fixes errors like this one:
```
Error: [vike][Wrong Usage] pageContext.httpResponse.getReadableWebStream() can't be used because the onRenderHtml() hook defined by vike-solid/__internal/integration/onRenderHtml provides a Web Stream Pipe. Make sure the onRenderHtml() defined by vike-solid/__internal/integration/onRenderHtml hook provides a Readable Web Stream instead. See https://vike.dev/streaming for more information.
```
=> fix: pipeable web stream

vike/node/runtime/renderPage.ts, vike/node/runtime/renderPage/createHttpResponse.ts, vike/node/runtime/renderPage/createHttpResponse/assertNoInfiniteHttpRedirect.spec.ts, vike/node/runtime/renderPage/createHttpResponse/assertNoInfiniteHttpRedirect.ts, vike/utils/parseUrl-extras.ts
Fixes:
- #2262
History of `assertNoInfiniteHttpRedirect()`:
- https://github.com/vikejs/vike/issues/1270
- https://github.com/vikejs/vike/issues/1103
- https://github.com/vikejs/vike/commit/522bd0fa3190e31aa4f59e781f7661d1a9569b12
I wonder why I used `urlLogical` instead of `urlOriginal`.
>   // The URL we assume the redirect to be logically based on
>   urlLogical: string
Isn't it overthinking it? Can't we just simply observe the URL redirection chain for loops, regardless of the semantics behind the URL redirections? This PR makes `assertNoInfiniteHttpRedirect()` use `urlOriginal` instead of `urlLogical`, let's see if a user complains.
=> fix: fix catch of infinite redirections (fix #2262)

vike/node/runtime/renderPage/createHttpResponse.ts, vike/node/runtime/renderPage/createHttpResponse/assertNoInfiniteHttpRedirect.spec.ts, vike/node/runtime/renderPage/createHttpResponse/assertNoInfiniteHttpRedirect.ts
Failed attempt to fix https://github.com/vikejs/vike/issues/1270#issuecomment-1820608999.
A solution would be to set a cookie that tracks infinite loops, but it's far from trivial to implement, thus postponing.
Removing the infinite redirection loop detection in the meantime.
See also:
- https://github.com/vikejs/vike/pull/2264
- Browser already have a built-in detection: ERR_TOO_MANY_REDIRECTS https://www.semrush.com/blog/too-many-redirects/
=> [failed attempt] make infinite redirection loop detection reliable (closes #2262)

docs/pages/CJS/+Page.mdx, docs/pages/env/+Page.mdx, vike/node/plugin/plugins/envVars.ts, vike/utils/isScriptFile.ts, vike/utils/parseUrl.ts
Resolves #2287
I've only ignored the `CHANGELOG.md` for historical reasons, but if you think it should also be changed I can complement this PR.
=> Refactor inclusive code

docs/pages/index/sections/features/chip/Chip.tsx
Oops. I missed one of the styles in https://github.com/vikejs/vike/pull/2341
=> Align right-side numbers in chip diagram

vike/node/runtime/renderPage.ts
when window.location.pathname = 'E5%A7%8B/%22%7D%22%7D' , it will get error:
``` ts
URIError: URI malformed
at decodeURI (<anonymous>)
at prettyUrl (file:///Users/xxxx/=xxxx/node_modules/.pnpm/vike@0.4.224_react-streaming@0.3.48_react-dom@19.0.0_react@19.0.0__react@19.0.0__vite@6.2.1_@_hf5uinn3urlsbelld7h44mswdi/node_modules/vike/dist/esm/node/runtime/renderPage.js:242:20)
at getRequestInfoMessage (file:///Users/xxxx/yyyy/node_modules/.pnpm/vike@0.4.224_react-streaming@0.3.48_react-dom@19.0.0_react@19.0.0__react@19.0.0__vite@6.2.1_@_hf5uinn3urlsbelld7h44mswdi/node_modules/vike/dist/esm/node/runtime/renderPage.js:200:29)
at logHttpRequest (file:///Users/xxxx/yyyy/node_modules/.pnpm/vike@0.4.224_react-streaming@0.3.48_react-dom@19.0.0_react@19.0.0__react@19.0.0__vite@6.2.1_@_hf5uinn3urlsbell …
```
=> fix: add safe  operations to decodeURI.

vike/node/runtime/universal-middleware.ts
https://vike.dev/server#custom-pagecontext
>The runtime object is also available at pageContext.runtime.
=> feat: `pageContext.runtime` (vike-server)

vike/node/runtime/html/renderHtml.ts
@brillout Vike wasn't using `doNotClose`, which is what caused [this issue](https://github.com/vikejs/vike-server/issues/119).
I tested the fix with Hono, Express and Fastify, they seem to always work as intended now.
Prior to this fix, calls to `injectToStream` would potentially be dropped.
=> fix: do not close web stream prematurly

packages/vike/node/prerender/runPrerender.ts, test/playground/pages/e2e-test.ts
This pull request introduces improvements to how HTML redirects are handled in the prerendering logic, for better SEO
* Added a `<link rel="canonical" href="..."/>` tag to the HTML generated for redirects in `getRedirectHtml`, which helps search engines recognize the canonical destination of the redirect.
* Updated the end-to-end test in `e2e-test.ts` to verify the presence of the canonical link in redirect HTML, ensuring the new behavior is covered by tests.
Other site generators / frameworks add the canonical link. See:
- https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/alias.html
- https://github.com/jekyll/jekyll-redirect-from/blob/master/lib/jekyll-redirect-from/redirect.html
=> fix: include canonical link in prerendered redirect
